# Starter palette. Matugen will replace this file after its first run.
$lock_outline = rgba(00f0ffcc)
$lock_check = rgba(a3be8ccc)
$lock_fail = rgba(bf616acc)
$lock_font = rgb(f2f7ff)
$lock_date = rgba(8b9bb4dd)
$lock_media = rgba(9d4eddff)
$lock_time = rgba(00f0ffff)
$lock_layout = rgba(8b9bb4ff)
