$font = JetBrains Mono
source = ~/.config/hypr/hyprlock-colors.conf

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = smooth, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 5, smooth
    animation = fadeOut, 1, 5, smooth
    animation = inputFieldDots, 1, 2, smooth
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 5
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = $lock_outline
    check_color = $lock_check
    fail_color = $lock_fail
    font_color = $lock_font
    fade_on_empty = false
    rounding = 25
    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL
    dots_size = 0.2
    dots_spacing = 0.3
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 60
    font_family = $font
    color = $lock_time
    position = 0, -130
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 16
    font_family = $font
    color = $lock_date
    position = 0, -250
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/now-playing.sh
    font_size = 15
    color = $lock_media
    position = 0, -300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/password-cursor.sh
    font_size = 18
    font_family = $font
    color = $lock_layout
    position = 0, 2
    halign = center
    valign = center
}
